version: '3.5'

services:
  library:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./lib:/app/lib:delegated
      - ./code:/app/code:delegated
    command: tail -F /dev/null
